# Generated by Django 4.2.9 on 2024-07-15 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_comments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCommentsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_id", models.IntegerField()),
                ("text", models.TextField()),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 7, 15, 0, 19, 44, 249107)
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="movieuserinfomodel",
            name="user_id",
        ),
    ]
