# Generated by Django 4.2.9 on 2024-07-15 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie_user_info", "0002_alter_movieuserinfomodel_user_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_comments", "0002_usercommentsmodel_remove_movieuserinfomodel_user_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MovieUserInfoModel",
        ),
        migrations.AddField(
            model_name="usercommentsmodel",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
