# Generated by Django 4.2.9 on 2024-07-15 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_comments", "0002_usercommentsmodel_remove_movieuserinfomodel_user_id"),
        ("movie_user_info", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieuserinfomodel",
            name="user_comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user_comments.usercommentsmodel",
            ),
        ),
    ]
